#!/usr/bin/env bash
# ESP32 workload benchmark.
#
# Runs two related scenarios:
#   1. One broker under heavy client/topic/message load.
#   2. An ESP32-like broker mesh at 5 and 10 nodes.
#
# This is the direct fit for "5~10 台 ESP32" plus "一台處理多 client / 多 msg / 多 topic".
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
OUT="${OUT:-$ROOT/build_out/esp32_workload_bench}"
DOCKER_BENCH="${DOCKER_BENCH:-$SCRIPT_DIR/bench_p2p_docker_scale.sh}"

SINGLE_BROKER_COUNTS="${SINGLE_BROKER_COUNTS:-1}"
SINGLE_BROKER_TOPICS="${SINGLE_BROKER_TOPICS:-100 200}"
SINGLE_BROKER_MESSAGES="${SINGLE_BROKER_MESSAGES:-1000 10000}"
SINGLE_BROKER_SENSOR_CLIENTS="${SINGLE_BROKER_SENSOR_CLIENTS:-1000}"
SINGLE_BROKER_SENSOR_CONNECTIONS="${SINGLE_BROKER_SENSOR_CONNECTIONS:-128}"
SINGLE_BROKER_SENSOR_WORKERS="${SINGLE_BROKER_SENSOR_WORKERS:-64}"

ESP32_BROKER_COUNTS="${ESP32_BROKER_COUNTS:-5 10}"
ESP32_TOPICS="${ESP32_TOPICS:-100 200}"
ESP32_MESSAGES="${ESP32_MESSAGES:-1000 10000}"
ESP32_SENSOR_CLIENTS="${ESP32_SENSOR_CLIENTS:-0}"
ESP32_SENSOR_CONNECTIONS="${ESP32_SENSOR_CONNECTIONS:-0}"
ESP32_SENSOR_WORKERS="${ESP32_SENSOR_WORKERS:-64}"
ESP32_DISTRIBUTED_PUBLISHERS="${ESP32_DISTRIBUTED_PUBLISHERS:-1}"
ESP32_SCALE_MESSAGES_BY_BROKER="${ESP32_SCALE_MESSAGES_BY_BROKER:-1}"

TARGET_P95_MS="${TARGET_P95_MS:-10}"
SINGLE_BROKER_STARTUP_SEC="${SINGLE_BROKER_STARTUP_SEC:-2}"
SINGLE_BROKER_SYNC_SETTLE_SEC="${SINGLE_BROKER_SYNC_SETTLE_SEC:-5}"
ESP32_STARTUP_SEC="${ESP32_STARTUP_SEC:-2}"
ESP32_SYNC_SETTLE_SEC="${ESP32_SYNC_SETTLE_SEC:-15}"

mkdir -p "$OUT"

echo "# phase=single_broker"
OUT="$OUT/single_broker" \
BROKER_COUNTS="$SINGLE_BROKER_COUNTS" \
TOPIC_COUNTS="$SINGLE_BROKER_TOPICS" \
MESSAGE_COUNTS="$SINGLE_BROKER_MESSAGES" \
SENSOR_CLIENTS="$SINGLE_BROKER_SENSOR_CLIENTS" \
SENSOR_CONNECTIONS="$SINGLE_BROKER_SENSOR_CONNECTIONS" \
SENSOR_WORKERS="$SINGLE_BROKER_SENSOR_WORKERS" \
STARTUP_SEC="$SINGLE_BROKER_STARTUP_SEC" \
SYNC_SETTLE_SEC="$SINGLE_BROKER_SYNC_SETTLE_SEC" \
ESP32_PROFILE=0 \
"$DOCKER_BENCH"

echo "# phase=esp32_mesh"
OUT="$OUT/esp32_mesh" \
BROKER_COUNTS="$ESP32_BROKER_COUNTS" \
TOPIC_COUNTS="$ESP32_TOPICS" \
MESSAGE_COUNTS="$ESP32_MESSAGES" \
SENSOR_CLIENTS="$ESP32_SENSOR_CLIENTS" \
SENSOR_CONNECTIONS="$ESP32_SENSOR_CONNECTIONS" \
SENSOR_WORKERS="$ESP32_SENSOR_WORKERS" \
DISTRIBUTED_PUBLISHERS="$ESP32_DISTRIBUTED_PUBLISHERS" \
SCALE_MESSAGES_BY_BROKER="$ESP32_SCALE_MESSAGES_BY_BROKER" \
STARTUP_SEC="$ESP32_STARTUP_SEC" \
SYNC_SETTLE_SEC="$ESP32_SYNC_SETTLE_SEC" \
ESP32_PROFILE=1 \
"$DOCKER_BENCH"
